using System.Numerics;
using Content.Client.CombatMode;
using Content.Client.Hands.Systems;
using Content.Client.UserInterface.Systems.Hands;
using Content.Client.UserInterface.Systems.Inventory;
using Content.Client.UserInterface.Systems.Inventory.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.ContentPack;
using Robust.Shared.Maths;
using Robust.Shared.Utility;

namespace Content.Client.UserInterface.Systems.RogueHud.Widgets;

[GenerateTypedNameReferences]
public sealed partial class RogueHudGui : UIWidget
{
    [Dependency] private IResourceCache _resCache = default!;

    public event Action<string>? OnTargetZoneSelected;
    public event Action? OnCombatTogglePressed;
    public event Action? OnDropPressed;

    private string _selectedTargetZone = "chest";

    public RogueHudGui()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        BackgroundTexture.Stretch = TextureRect.StretchMode.Scale;
        DollBaseTexture.Stretch = TextureRect.StretchMode.KeepCentered;
        DollZoneHead.Stretch = TextureRect.StretchMode.KeepCentered;
        DollZoneChest.Stretch = TextureRect.StretchMode.KeepCentered;
        DollZoneRArm.Stretch = TextureRect.StretchMode.KeepCentered;
        DollZoneLArm.Stretch = TextureRect.StretchMode.KeepCentered;
        DollZoneRLeg.Stretch = TextureRect.StretchMode.KeepCentered;
        DollZoneLLeg.Stretch = TextureRect.StretchMode.KeepCentered;

        // Bind OverlayPanel to 480x480 frame sockets
        OverlayPanel.BindToBackground(BackgroundTexture, new Vector2(480, 480));
        OverlayPanel.SetVirtualRect(BackgroundTexture, UIBox2.FromDimensions(0, 0, 480, 480));
        OverlayPanel.SetVirtualRect(InventoryPanel, UIBox2.FromDimensions(10, 322, 304, 72));
        OverlayPanel.SetVirtualRect(LeftPanel, UIBox2.FromDimensions(10, 396, 114, 74));
        OverlayPanel.SetVirtualRect(CenterPanel, UIBox2.FromDimensions(198, 430, 80, 42));
        OverlayPanel.SetVirtualRect(RightPanel, UIBox2.FromDimensions(288, 392, 188, 84));

        var inventoryUIController = UserInterfaceManager.GetUIController<InventoryUIController>();
        inventoryUIController.RegisterInventoryBarContainer(InventoryHotbar);
        InventoryHotbar.InvalidateMeasure();
        InventoryHotbar.InvalidateArrange();
        MainHotbar.InvalidateMeasure();
        MainHotbar.InvalidateArrange();
        SecondHotbar.InvalidateMeasure();
        SecondHotbar.InvalidateArrange();

        var handsUIController = UserInterfaceManager.GetUIController<HandsUIController>();
        handsUIController.ReloadPlayerHands();
        HandContainer.InvalidateMeasure();
        HandContainer.InvalidateArrange();

        InitializeTargetButtonOpacities();
        InitializeTextures();
        SetupTargetingDollEvents();
        SetupInventoryToggle();

        BtnCombatToggle.OnPressed += _ => OnCombatTogglePressed?.Invoke();
    }

    protected override void Resized()
    {
        base.Resized();
        OverlayPanel.UpdateFromBackground(BackgroundTexture);
    }

    private void InitializeTargetButtonOpacities()
    {
        var transparentColor = new Color(0, 0, 0, 0);
        BtnTargetHead.ModulateSelfOverride = transparentColor;
        BtnTargetChest.ModulateSelfOverride = transparentColor;
        BtnTargetRArm.ModulateSelfOverride = transparentColor;
        BtnTargetLArm.ModulateSelfOverride = transparentColor;
        BtnTargetRLeg.ModulateSelfOverride = transparentColor;
        BtnTargetLLeg.ModulateSelfOverride = transparentColor;
    }

    private void InitializeTextures()
    {
        try
        {
            if (_resCache.TryGetResource<TextureResource>(new ResPath("/Textures/Interface/RogueHud/left_side.png"), out var leftTex))
                LeftPanelTexture.Texture = leftTex.Texture;

            if (_resCache.TryGetResource<TextureResource>(new ResPath("/Textures/Interface/RogueHud/centr.png"), out var centerTex))
                CenterPanelTexture.Texture = centerTex.Texture;

            if (_resCache.TryGetResource<TextureResource>(new ResPath("/Textures/Interface/RogueHud/right_side.png"), out var rightTex))
                RightPanelTexture.Texture = rightTex.Texture;

            // Gargoyle Base Doll
            if (_resCache.TryGetResource<RSIResource>(new ResPath("/Textures/Interface/RogueHud/roguehud64.rsi"), out var dollRsi))
            {
                if (dollRsi.RSI.TryGetState("m-zone_sel", out var baseDollState))
                {
                    DollBaseTexture.Texture = baseDollState.Frame0;
                }

                if (dollRsi.RSI.TryGetState("m-head", out var headState)) DollZoneHead.Texture = headState.Frame0;
                if (dollRsi.RSI.TryGetState("m-chest", out var chestState)) DollZoneChest.Texture = chestState.Frame0;
                if (dollRsi.RSI.TryGetState("m-r_arm", out var rArmState)) DollZoneRArm.Texture = rArmState.Frame0;
                if (dollRsi.RSI.TryGetState("m-l_arm", out var lArmState)) DollZoneLArm.Texture = lArmState.Frame0;
                if (dollRsi.RSI.TryGetState("m-r_leg", out var rLegState)) DollZoneRLeg.Texture = rLegState.Frame0;
                if (dollRsi.RSI.TryGetState("m-l_leg", out var lLegState)) DollZoneLLeg.Texture = lLegState.Frame0;
            }
        }
        catch (Exception e)
        {
            Logger.Warning($"Failed to load RogueHud textures: {e.Message}");
        }
    }

    private void SetTextureIfAvailable(RSIResource rsiRes, string stateName, Action<Texture> apply)
    {
        if (rsiRes.RSI.TryGetState(stateName, out var state))
        {
            apply(state.Frame0);
        }
    }

    private void SetupTargetingDollEvents()
    {
        BtnTargetHead.OnPressed += _ => SelectTargetZone("head");
        BtnTargetChest.OnPressed += _ => SelectTargetZone("chest");
        BtnTargetRArm.OnPressed += _ => SelectTargetZone("r_arm");
        BtnTargetLArm.OnPressed += _ => SelectTargetZone("l_arm");
        BtnTargetRLeg.OnPressed += _ => SelectTargetZone("r_leg");
        BtnTargetLLeg.OnPressed += _ => SelectTargetZone("l_leg");

        SelectTargetZone("chest");
    }

    public void SelectTargetZone(string zone)
    {
        _selectedTargetZone = zone;

        DollZoneHead.Visible = zone == "head";
        DollZoneChest.Visible = zone == "chest";
        DollZoneRArm.Visible = zone == "r_arm";
        DollZoneLArm.Visible = zone == "l_arm";
        DollZoneRLeg.Visible = zone == "r_leg";
        DollZoneLLeg.Visible = zone == "l_leg";

        OnTargetZoneSelected?.Invoke(zone);
    }

    public void UpdateCombatModeState(bool inCombat)
    {
        BtnCombatToggle.Modulate = inCombat ? Color.Red : Color.White;
    }

    private bool _isInventoryOpen = true;

    private void SetupInventoryToggle()
    {
        ToggleInventoryButton.OnPressed += _ =>
        {
            _isInventoryOpen = !_isInventoryOpen;
            UpdateInventoryState();
        };

        UpdateInventoryState();
    }

    private void UpdateInventoryState()
    {
        var framePath = _isInventoryOpen
            ? "/Textures/Interface/RogueHud/alive.png"
            : "/Textures/Interface/RogueHud/alive2.png";

        var panelPath = _isInventoryOpen
            ? "/Textures/Interface/RogueHud/inventory.png"
            : "/Textures/Interface/RogueHud/inventory_closed.png";

        if (_resCache.TryGetResource<TextureResource>(new ResPath(framePath), out var frameTex))
        {
            BackgroundTexture.Texture = frameTex.Texture;
        }

        if (_resCache.TryGetResource<TextureResource>(new ResPath(panelPath), out var panelTex))
        {
            InventoryPanelTexture.Texture = panelTex.Texture;
        }

        EquipmentPanelContainer.Visible = _isInventoryOpen;
    }
}
