using System.Numerics;
using Content.Client.CombatMode;
using Content.Client.Hands.Systems;
using Content.Client.UserInterface.Systems.Hands;
using Content.Client.UserInterface.Systems.Hands.Controls;
using Content.Client.UserInterface.Systems.Inventory;
using Content.Client.UserInterface.Systems.Inventory.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.ContentPack;
using Robust.Shared.Maths;
using Robust.Shared.Utility;

namespace Content.Client.UserInterface.Systems.RogueHud.Widgets;

[GenerateTypedNameReferences]
public sealed partial class RogueHudGui : UIWidget
{
    [Dependency] private IResourceCache _resCache = default!;

    public event Action<string>? OnTargetZoneSelected;
    public event Action? OnCombatTogglePressed;
    public event Action? OnDropPressed;

    private string _selectedTargetZone = "chest";

    public RogueHudGui()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        BackgroundTexture.Stretch = TextureRect.StretchMode.Scale;
        DollBaseTexture.Stretch = TextureRect.StretchMode.KeepCentered;
        DollZoneHead.Stretch = TextureRect.StretchMode.KeepCentered;
        DollZoneChest.Stretch = TextureRect.StretchMode.KeepCentered;
        DollZoneRArm.Stretch = TextureRect.StretchMode.KeepCentered;
        DollZoneLArm.Stretch = TextureRect.StretchMode.KeepCentered;
        DollZoneRLeg.Stretch = TextureRect.StretchMode.KeepCentered;
        DollZoneLLeg.Stretch = TextureRect.StretchMode.KeepCentered;

        // Background stretches to fill the whole screen
        LayoutContainer.SetAnchorAndMarginPreset(BackgroundTexture, LayoutContainer.LayoutPreset.Wide);

        // LeftPanel (216x140): bottom-left corner, 10px margin
        LayoutContainer.SetAnchorPreset(LeftPanel, LayoutContainer.LayoutPreset.BottomLeft);
        LayoutContainer.SetMarginLeft(LeftPanel, 10);
        LayoutContainer.SetMarginBottom(LeftPanel, -10);
        LayoutContainer.SetMarginRight(LeftPanel, 10 + 216);
        LayoutContainer.SetMarginTop(LeftPanel, -10 - 140);

        // InventoryPanel (596x140): stacked above LeftPanel with 6px gap
        LayoutContainer.SetAnchorPreset(InventoryPanel, LayoutContainer.LayoutPreset.BottomLeft);
        LayoutContainer.SetMarginLeft(InventoryPanel, 10);
        LayoutContainer.SetMarginBottom(InventoryPanel, -10 - 140 - 6);          // -156
        LayoutContainer.SetMarginRight(InventoryPanel, 10 + 596);                 // 606
        LayoutContainer.SetMarginTop(InventoryPanel, -10 - 140 - 6 - 140);       // -296

        // CenterPanel (146x76): bottom-center, fits 2x 64x64 hand slots
        LayoutContainer.SetAnchorPreset(CenterPanel, LayoutContainer.LayoutPreset.CenterBottom);
        LayoutContainer.SetMarginLeft(CenterPanel, -73);
        LayoutContainer.SetMarginRight(CenterPanel, 73);
        LayoutContainer.SetMarginBottom(CenterPanel, -10);
        LayoutContainer.SetMarginTop(CenterPanel, -10 - 76);

        // RightPanel (360x162): bottom-right corner, 10px margin
        LayoutContainer.SetAnchorPreset(RightPanel, LayoutContainer.LayoutPreset.BottomRight);
        LayoutContainer.SetMarginRight(RightPanel, -10);
        LayoutContainer.SetMarginLeft(RightPanel, -10 - 360);
        LayoutContainer.SetMarginBottom(RightPanel, -10);
        LayoutContainer.SetMarginTop(RightPanel, -10 - 162);

        // ToggleInventoryButton: direct child of LayoutContainer, anchored to BottomLeft
        LayoutContainer.SetAnchorPreset(ToggleInventoryButton, LayoutContainer.LayoutPreset.BottomLeft);

        var inventoryUIController = UserInterfaceManager.GetUIController<InventoryUIController>();
        inventoryUIController.RegisterInventoryBarContainer(InventoryHotbar);
        InventoryHotbar.InvalidateMeasure();
        InventoryHotbar.InvalidateArrange();
        MainHotbar.InvalidateMeasure();
        MainHotbar.InvalidateArrange();
        SecondHotbar.InvalidateMeasure();
        SecondHotbar.InvalidateArrange();

        var handsUIController = UserInterfaceManager.GetUIController<HandsUIController>();
        handsUIController.ReloadPlayerHands();
        HandContainer.InvalidateMeasure();
        HandContainer.InvalidateArrange();

        InitializeTargetButtonOpacities();
        InitializeTextures();
        SetupTargetingDollEvents();
        SetupInventoryToggle();

        BtnCombatToggle.OnPressed += _ => OnCombatTogglePressed?.Invoke();
    }


    private void InitializeTargetButtonOpacities()
    {
        var transparentColor = new Color(0, 0, 0, 0);

        // Target zone body buttons
        BtnTargetHead.ModulateSelfOverride = transparentColor;
        BtnTargetChest.ModulateSelfOverride = transparentColor;
        BtnTargetRArm.ModulateSelfOverride = transparentColor;
        BtnTargetLArm.ModulateSelfOverride = transparentColor;
        BtnTargetRLeg.ModulateSelfOverride = transparentColor;
        BtnTargetLLeg.ModulateSelfOverride = transparentColor;

        // Action buttons — invisible overlays on top of left_side.png art
        BtnCraft.ModulateSelfOverride = transparentColor;
        BtnSkills.ModulateSelfOverride = transparentColor;
        BtnRun.ModulateSelfOverride = transparentColor;
        BtnSneak.ModulateSelfOverride = transparentColor;
        BtnCombatToggle.ModulateSelfOverride = transparentColor;
        ToggleInventoryButton.ModulateSelfOverride = transparentColor;
    }

    private void InitializeTextures()
    {
        try
        {
            if (_resCache.TryGetResource<TextureResource>(new ResPath("/Textures/Interface/RogueHud/left_side.png"), out var leftTex))
                LeftPanelTexture.Texture = leftTex.Texture;

            if (_resCache.TryGetResource<TextureResource>(new ResPath("/Textures/Interface/RogueHud/centr.png"), out var centerTex))
                CenterPanelTexture.Texture = centerTex.Texture;

            if (_resCache.TryGetResource<TextureResource>(new ResPath("/Textures/Interface/RogueHud/right_side.png"), out var rightTex))
                RightPanelTexture.Texture = rightTex.Texture;

            // Gargoyle Base Doll
            if (_resCache.TryGetResource<RSIResource>(new ResPath("/Textures/Interface/RogueHud/roguehud64.rsi"), out var dollRsi))
            {
                if (dollRsi.RSI.TryGetState("m-zone_sel", out var baseDollState))
                {
                    DollBaseTexture.Texture = baseDollState.Frame0;
                }

                if (dollRsi.RSI.TryGetState("m-head", out var headState)) DollZoneHead.Texture = headState.Frame0;
                if (dollRsi.RSI.TryGetState("m-chest", out var chestState)) DollZoneChest.Texture = chestState.Frame0;
                if (dollRsi.RSI.TryGetState("m-r_arm", out var rArmState)) DollZoneRArm.Texture = rArmState.Frame0;
                if (dollRsi.RSI.TryGetState("m-l_arm", out var lArmState)) DollZoneLArm.Texture = lArmState.Frame0;
                if (dollRsi.RSI.TryGetState("m-r_leg", out var rLegState)) DollZoneRLeg.Texture = rLegState.Frame0;
                if (dollRsi.RSI.TryGetState("m-l_leg", out var lLegState)) DollZoneLLeg.Texture = lLegState.Frame0;
            }

            // Combat Mode Overlay & Active Hand Glow
            if (_resCache.TryGetResource<RSIResource>(new ResPath("/Textures/Interface/RogueHud/roguehud.rsi"), out var hudRsi))
            {
                if (hudRsi.RSI.TryGetState("combat1", out var combatState))
                {
                    CombatStateTexture.Texture = combatState.Frame0;
                }

                if (hudRsi.RSI.TryGetState("hand_active", out var handActiveState))
                {
                    var activeTex = handActiveState.Frame0;
                    HandContainer.OnChildAdded += child =>
                    {
                        if (child is HandButton handBtn)
                        {
                            handBtn.HighlightRect.Texture = activeTex;
                            handBtn.HighlightRect.Stretch = TextureRect.StretchMode.Scale;
                            handBtn.HighlightRect.SetSize = new Vector2(64, 64);
                        }
                    };
                    foreach (var btn in HandContainer.GetButtons())
                    {
                        btn.HighlightRect.Texture = activeTex;
                        btn.HighlightRect.Stretch = TextureRect.StretchMode.Scale;
                        btn.HighlightRect.SetSize = new Vector2(64, 64);
                    }
                }
            }
        }
        catch (Exception e)
        {
            Logger.Warning($"Failed to load RogueHud textures: {e.Message}");
        }
    }

    private void SetTextureIfAvailable(RSIResource rsiRes, string stateName, Action<Texture> apply)
    {
        if (rsiRes.RSI.TryGetState(stateName, out var state))
        {
            apply(state.Frame0);
        }
    }

    private void SetupTargetingDollEvents()
    {
        BtnTargetHead.OnPressed += _ => SelectTargetZone("head");
        BtnTargetChest.OnPressed += _ => SelectTargetZone("chest");
        BtnTargetRArm.OnPressed += _ => SelectTargetZone("r_arm");
        BtnTargetLArm.OnPressed += _ => SelectTargetZone("l_arm");
        BtnTargetRLeg.OnPressed += _ => SelectTargetZone("r_leg");
        BtnTargetLLeg.OnPressed += _ => SelectTargetZone("l_leg");

        SelectTargetZone("chest");
    }

    public void SelectTargetZone(string zone)
    {
        _selectedTargetZone = zone;

        DollZoneHead.Visible = zone == "head";
        DollZoneChest.Visible = zone == "chest";
        DollZoneRArm.Visible = zone == "r_arm";
        DollZoneLArm.Visible = zone == "l_arm";
        DollZoneRLeg.Visible = zone == "r_leg";
        DollZoneLLeg.Visible = zone == "l_leg";

        OnTargetZoneSelected?.Invoke(zone);
    }

    public void UpdateCombatModeState(bool inCombat)
    {
        CombatStateTexture.Visible = inCombat;
    }

    private bool _isInventoryOpen = true;

    private void SetupInventoryToggle()
    {
        ToggleInventoryButton.OnPressed += _ =>
        {
            _isInventoryOpen = !_isInventoryOpen;
            UpdateInventoryState();
        };

        UpdateInventoryState();
    }

    private void UpdateInventoryState()
    {
        var framePath = _isInventoryOpen
            ? "/Textures/Interface/RogueHud/alive.png"
            : "/Textures/Interface/RogueHud/alive2.png";

        var panelPath = _isInventoryOpen
            ? "/Textures/Interface/RogueHud/inventory.png"
            : "/Textures/Interface/RogueHud/inventory_closed.png";

        if (_resCache.TryGetResource<TextureResource>(new ResPath(framePath), out var frameTex))
        {
            BackgroundTexture.Texture = frameTex.Texture;
        }

        if (_resCache.TryGetResource<TextureResource>(new ResPath(panelPath), out var panelTex))
        {
            InventoryPanelTexture.Texture = panelTex.Texture;
        }

        EquipmentPanelContainer.Visible = _isInventoryOpen;

        // Move toggle button to match the visual arrow position on screen:
        // - Open:   arrow is at x=555 on the full 596px shelf  → margin left = 10 + 545 = 555
        // - Closed: arrow is at x=75 on the 2-slot closed frame → margin left = 10 + 65 = 75
        var toggleLeft = _isInventoryOpen ? 555 : 75;
        LayoutContainer.SetAnchorAndMarginPreset(ToggleInventoryButton, LayoutContainer.LayoutPreset.BottomLeft);
        LayoutContainer.SetMarginLeft(ToggleInventoryButton, toggleLeft);
        LayoutContainer.SetMarginRight(ToggleInventoryButton, toggleLeft + 40);
        LayoutContainer.SetMarginBottom(ToggleInventoryButton, -10 - 140 - 5);    // -155
        LayoutContainer.SetMarginTop(ToggleInventoryButton, -10 - 140 - 5 - 130); // -285
    }
}
