using System.Numerics;
using Content.Client.CombatMode;
using Content.Client.Hands.Systems;
using Content.Client.UserInterface.Systems.Hands;
using Content.Client.UserInterface.Systems.Inventory;
using Content.Client.UserInterface.Systems.Inventory.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.ContentPack;
using Robust.Shared.Maths;
using Robust.Shared.Utility;

namespace Content.Client.UserInterface.Systems.RogueHud.Widgets;

[GenerateTypedNameReferences]
public sealed partial class RogueHudGui : UIWidget
{
    [Dependency] private IResourceCache _resCache = default!;

    public event Action<string>? OnTargetZoneSelected;
    public event Action? OnCombatTogglePressed;
    public event Action? OnDropPressed;

    private string _selectedTargetZone = "chest";

    public RogueHudGui()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        BackgroundTexture.Stretch = TextureRect.StretchMode.Scale;
        DollBaseTexture.Stretch = TextureRect.StretchMode.KeepCentered;
        DollZoneHead.Stretch = TextureRect.StretchMode.KeepCentered;
        DollZoneChest.Stretch = TextureRect.StretchMode.KeepCentered;
        DollZoneRArm.Stretch = TextureRect.StretchMode.KeepCentered;
        DollZoneLArm.Stretch = TextureRect.StretchMode.KeepCentered;
        DollZoneRLeg.Stretch = TextureRect.StretchMode.KeepCentered;
        DollZoneLLeg.Stretch = TextureRect.StretchMode.KeepCentered;
        EyeTexture.Stretch = TextureRect.StretchMode.KeepCentered;

        // Register 1:1 pixel layout rects matching the 160x480 tower frame
        // Tower vertical zones (virtual 160x480):
        //   Y=0..125   → Gargoyle doll + targeting buttons
        //   Y=125..230 → Action buttons (craft, skills, run, sneak, combat etc.)
        //   Y=230..280 → Active hands (L/R) + Drop/Catch
        //   Y=280..480 → Equipment slots grid (10 inv + 3 main + 3 second = 16 slots, 3 cols)
        OverlayPanel.BindToBackground(BackgroundTexture, new Vector2(160, 480));
        OverlayPanel.SetVirtualRect(BackgroundTexture,         UIBox2.FromDimensions(0,   0,   160, 480));
        OverlayPanel.SetVirtualRect(DollContainer,             UIBox2.FromDimensions(5,   5,   150, 120));
        OverlayPanel.SetVirtualRect(ActionButtonsContainer,    UIBox2.FromDimensions(2,   128, 156, 100));
        OverlayPanel.SetVirtualRect(HandsPanelContainer,       UIBox2.FromDimensions(2,   230, 156, 48));
        OverlayPanel.SetVirtualRect(EquipmentPanelContainer,   UIBox2.FromDimensions(4,   280, 152, 196));

        var inventoryUIController = UserInterfaceManager.GetUIController<InventoryUIController>();
        inventoryUIController.RegisterInventoryBarContainer(InventoryHotbar);
        InventoryHotbar.InvalidateMeasure();
        InventoryHotbar.InvalidateArrange();
        MainHotbar.InvalidateMeasure();
        MainHotbar.InvalidateArrange();
        SecondHotbar.InvalidateMeasure();
        SecondHotbar.InvalidateArrange();

        var handsUIController = UserInterfaceManager.GetUIController<HandsUIController>();
        handsUIController.ReloadPlayerHands();
        HandContainer.InvalidateMeasure();
        HandContainer.InvalidateArrange();

        InitializeTargetButtonOpacities();
        InitializeTextures();
        SetupTargetingDollEvents();

        BtnCombatToggle.OnPressed += _ => OnCombatTogglePressed?.Invoke();
        BtnDrop.OnPressed += _ => OnDropPressed?.Invoke();
    }

    protected override void Resized()
    {
        base.Resized();
        OverlayPanel.UpdateFromBackground(BackgroundTexture);
    }

    private void InitializeTargetButtonOpacities()
    {
        var transparentColor = new Color(0, 0, 0, 0);
        BtnTargetHead.ModulateSelfOverride = transparentColor;
        BtnTargetChest.ModulateSelfOverride = transparentColor;
        BtnTargetRArm.ModulateSelfOverride = transparentColor;
        BtnTargetLArm.ModulateSelfOverride = transparentColor;
        BtnTargetRLeg.ModulateSelfOverride = transparentColor;
        BtnTargetLLeg.ModulateSelfOverride = transparentColor;
    }

    private void InitializeTextures()
    {
        try
        {
            // Background Tower Frame (human state) — 160x480 tower only
            if (_resCache.TryGetResource<RSIResource>(new ResPath("/Textures/Interface/RogueHud/roguehudtower.rsi"), out var backRsi))
            {
                if (backRsi.RSI.TryGetState("human", out var humanState))
                {
                    BackgroundTexture.Texture = humanState.Frame0;
                }
            }

            // Gargoyle Base Doll
            if (_resCache.TryGetResource<RSIResource>(new ResPath("/Textures/Interface/RogueHud/roguehud64.rsi"), out var dollRsi))
            {
                if (dollRsi.RSI.TryGetState("m-zone_sel", out var baseDollState))
                {
                    DollBaseTexture.Texture = baseDollState.Frame0;
                }

                if (dollRsi.RSI.TryGetState("m-head", out var headState)) DollZoneHead.Texture = headState.Frame0;
                if (dollRsi.RSI.TryGetState("m-chest", out var chestState)) DollZoneChest.Texture = chestState.Frame0;
                if (dollRsi.RSI.TryGetState("m-r_arm", out var rArmState)) DollZoneRArm.Texture = rArmState.Frame0;
                if (dollRsi.RSI.TryGetState("m-l_arm", out var lArmState)) DollZoneLArm.Texture = lArmState.Frame0;
                if (dollRsi.RSI.TryGetState("m-r_leg", out var rLegState)) DollZoneRLeg.Texture = rLegState.Frame0;
                if (dollRsi.RSI.TryGetState("m-l_leg", out var lLegState)) DollZoneLLeg.Texture = lLegState.Frame0;
            }

            // Buttons & Controls textures
            if (_resCache.TryGetResource<RSIResource>(new ResPath("/Textures/Interface/RogueHud/roguehud.rsi"), out var hudRsi))
            {
                SetTextureIfAvailable(hudRsi, "eye", tex => EyeTexture.Texture = tex);
                SetTextureIfAvailable(hudRsi, "combat0", tex => BtnCombatToggle.TextureNormal = tex);
                SetTextureIfAvailable(hudRsi, "craft", tex => BtnCraft.TextureNormal = tex);
                SetTextureIfAvailable(hudRsi, "skills", tex => BtnSkills.TextureNormal = tex);
                SetTextureIfAvailable(hudRsi, "sprint0", tex => BtnRun.TextureNormal = tex);
                SetTextureIfAvailable(hudRsi, "sneak0", tex => BtnSneak.TextureNormal = tex);
                SetTextureIfAvailable(hudRsi, "def1", tex => BtnParry.TextureNormal = tex);
                SetTextureIfAvailable(hudRsi, "def2", tex => BtnDodge.TextureNormal = tex);
                SetTextureIfAvailable(hudRsi, "rmbfeint", tex => BtnFeint.TextureNormal = tex);
                SetTextureIfAvailable(hudRsi, "intouch", tex => BtnTouch.TextureNormal = tex);
                SetTextureIfAvailable(hudRsi, "inshove", tex => BtnShove.TextureNormal = tex);
                SetTextureIfAvailable(hudRsi, "ingrab", tex => BtnGrab.TextureNormal = tex);
                SetTextureIfAvailable(hudRsi, "inpunch", tex => BtnPunch.TextureNormal = tex);
                SetTextureIfAvailable(hudRsi, "act_drop", tex => BtnDrop.TextureNormal = tex);
                SetTextureIfAvailable(hudRsi, "catch0", tex => BtnCatch.TextureNormal = tex);
            }
        }
        catch (Exception e)
        {
            Logger.Warning($"Failed to load RogueHud textures: {e.Message}");
        }
    }

    private void SetTextureIfAvailable(RSIResource rsiRes, string stateName, Action<Texture> apply)
    {
        if (rsiRes.RSI.TryGetState(stateName, out var state))
        {
            apply(state.Frame0);
        }
    }

    private void SetupTargetingDollEvents()
    {
        BtnTargetHead.OnPressed += _ => SelectTargetZone("head");
        BtnTargetChest.OnPressed += _ => SelectTargetZone("chest");
        BtnTargetRArm.OnPressed += _ => SelectTargetZone("r_arm");
        BtnTargetLArm.OnPressed += _ => SelectTargetZone("l_arm");
        BtnTargetRLeg.OnPressed += _ => SelectTargetZone("r_leg");
        BtnTargetLLeg.OnPressed += _ => SelectTargetZone("l_leg");

        SelectTargetZone("chest");
    }

    public void SelectTargetZone(string zone)
    {
        _selectedTargetZone = zone;

        DollZoneHead.Visible = zone == "head";
        DollZoneChest.Visible = zone == "chest";
        DollZoneRArm.Visible = zone == "r_arm";
        DollZoneLArm.Visible = zone == "l_arm";
        DollZoneRLeg.Visible = zone == "r_leg";
        DollZoneLLeg.Visible = zone == "l_leg";

        OnTargetZoneSelected?.Invoke(zone);
    }

    public void UpdateCombatModeState(bool inCombat)
    {
        if (!_resCache.TryGetResource<RSIResource>(new ResPath("/Textures/Interface/RogueHud/roguehud.rsi"), out var hudRsi))
            return;

        var stateName = inCombat ? "combat1" : "combat0";
        if (hudRsi.RSI.TryGetState(stateName, out var combatState))
        {
            BtnCombatToggle.TextureNormal = combatState.Frame0;
        }
    }
}
